---
output: 
  github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
library(microarrayBiasEvaluation)
```

# microarrayBiasEvaluation

<!-- badges: start -->
<!-- badges: end -->

Functions used to analyze custom Agilent microarrays to determine the extent of specific bias sources

## Instalation:

The package requires R 3.5.0 or later

``` r
install.packages("devtools")  
devtools::install_github("rjaksik/microarrayBiasEvaluation")

```

## Example use:

``` r
library('microarrayBiasEvaluation')

path='/RawData'
targets_file = "sample_desc.txt"
expData = procCustArray(targets_file,path)

probeData = read.table(system.file("resources", "A-MTAB-703_probe_details.txt", package = "microarrayBiasEvaluation"),header=T,sep='\t')
plotGCcontentBias(expData$exptab, 'CustMicro_GC_DistExprs_v2.pdf')
plotLengthBias(expData,'CustMicro_Len_DistExprs_v1.pdf')
plotAnBias(expData,probeData,'CustMicro_An')
plotT7Bias(expData,probeData,'CustMicro_T7')
plotG4Bias(expData,probeData,'CustMicro_G4')

```

## procCustArray

```{r, results="asis", echo=FALSE}
help_console(procCustArray, format = "html")
```

## probediff

```{r, results="asis", echo=FALSE}
help_console(probediff, format = "html")
```

## plotGCcontentBias

```{r, results="asis", echo=FALSE}
help_console(plotGCcontentBias, format = "html")
```

## plotLengthBias

```{r, results="asis", echo=FALSE}
help_console(plotLengthBias, format = "html")
```

## plotAnBias

```{r, results="asis", echo=FALSE}
help_console(plotAnBias, format = "html")
```

## plotG4Bias

```{r, results="asis", echo=FALSE}
help_console(plotG4Bias, format = "html")
```

## plotT7Bias

```{r, results="asis", echo=FALSE}
help_console(plotT7Bias, format = "html")
```
